const users = [
    { id: 1, name: 'John', surname: 'Smith', email: 'johnsmith@gmail.com', gender: 'Male' },
    { id: 2, name: 'Emma', surname: 'Johnson', email: 'emmajohnson@gmail.com', gender: 'Female' },
    { id: 3, name: 'Michael', surname: 'Williams', email: 'michaelwilliams@gmail.com', gender: 'Male' },
    { id: 4, name: 'Olivia', surname: 'Brown', email: 'oliviabrown@gmail.com', gender: 'Female' },
    { id: 5, name: 'William', surname: 'Jones', email: 'williamjones@gmail.com', gender: 'Male' },
    { id: 6, name: 'James', surname: 'Davis', email: 'jamesdavis@gmail.com', gender: 'Male' },
    { id: 7, name: 'Ava', surname: 'Miller', email: 'avamiller@gmail.com', gender: 'Female' },
    { id: 8, name: 'Sophia', surname: 'Wilson', email: 'sophiawilson@gmail.com', gender: 'Female' },
    { id: 9, name: 'Logan', surname: 'Moore', email: 'loganmoore@gmail.com', gender: 'Male' },
    { id: 10, name: 'Mia', surname: 'Taylor', email: 'miataylor@gmail.com', gender: 'Female' },
    { id: 11, name: 'Ethan', surname: 'Anderson', email: 'ethananderson@gmail.com', gender: 'Male' },
    { id: 12, name: 'Amelia', surname: 'Thomas', email: 'ameliathomas@gmail.com', gender: 'Female' },
    { id: 13, name: 'Lucas', surname: 'Jackson', email: 'lucasjackson@gmail.com', gender: 'Male' },
    { id: 14, name: 'Charlotte', surname: 'White', email: 'charlottewhite@gmail.com', gender: 'Female' },
    { id: 15, name: 'Benjamin', surname: 'Harris', email: 'benjaminharris@gmail.com', gender: 'Male' },
    { id: 16, name: 'Mason', surname: 'Martin', email: 'masonmartin@gmail.com', gender: 'Male' },
    { id: 17, name: 'Harper', surname: 'Thompson', email: 'harperthompson@gmail.com', gender: 'Female' },
    { id: 18, name: 'Evelyn', surname: 'Garcia', email: 'evelyngarcia@gmail.com', gender: 'Female' },
    { id: 19, name: 'Alexander', surname: 'Martinez', email: 'alexandermartinez@gmail.com', gender: 'Male' },
    { id: 20, name: 'Liam', surname: 'Robinson', email: 'liamrobinson@gmail.com', gender: 'Male' },
    { id: 21, name: 'Grace', surname: 'Clark', email: 'graceclark@gmail.com', gender: 'Female' },
    { id: 22, name: 'Elijah', surname: 'Rodriguez', email: 'elijahrodriguez@gmail.com', gender: 'Male' },
    { id: 23, name: 'Avery', surname: 'Lewis', email: 'averylewis@gmail.com', gender: 'Female' },
    { id: 24, name: 'Ella', surname: 'Lee', email: 'ellalee@gmail.com', gender: 'Female' },
    { id: 25, name: 'Ryan', surname: 'Walker', email: 'ryanwalker@gmail.com', gender: 'Male' },
    { id: 26, name: 'David', surname: 'Hall', email: 'davidhall@gmail.com', gender: 'Male' },
    { id: 27, name: 'Aiden', surname: 'Allen', email: 'aidenallen@gmail.com', gender: 'Male' },
    { id: 28, name: 'Nora', surname: 'Young', email: 'norayoung@gmail.com', gender: 'Female' },
    { id: 29, name: 'Levi', surname: 'Scott', email: 'leviscott@gmail.com', gender: 'Male' },
    { id: 30, name: 'Zoey', surname: 'King', email: 'zoeyking@gmail.com', gender: 'Female' },
    { id: 31, name: 'Sofia', surname: 'Baker', email: 'sofiabaker@gmail.com', gender: 'Female' },
    { id: 32, name: 'Carter', surname: 'Hill', email: 'carterhill@gmail.com', gender: 'Male' },
    { id: 33, name: 'Jackson', surname: 'Young', email: 'jacksonyoung@gmail.com', gender: 'Male' },
    { id: 34, name: 'Luna', surname: 'Cooper', email: 'lunacooper@gmail.com', gender: 'Female' },
    { id: 35, name: 'Ethan', surname: 'Lee', email: 'ethanlee@gmail.com', gender: 'Male' },
    { id: 36, name: 'Isabella', surname: 'Clark', email: 'isabellaclark@gmail.com', gender: 'Female' },
    { id: 37, name: 'Alexander', surname: 'Thomas', email: 'alexanderthomas@gmail.com', gender: 'Male' },
    { id: 38, name: 'Charlotte', surname: 'Martinez', email: 'charlottemartinez@gmail.com', gender: 'Female' },
    { id: 39, name: 'Daniel', surname: 'Hernandez', email: 'danielhernandez@gmail.com', gender: 'Male' },
    { id: 40, name: 'Sophia', surname: 'Young', email: 'sophiayoung@gmail.com', gender: 'Female' },
    { id: 41, name: 'Emily', surname: 'Rodriguez', email: 'emilyrodriguez@gmail.com', gender: 'Female' },
    { id: 42, name: 'Sebastian', surname: 'Lopez', email: 'sebastianlopez@gmail.com', gender: 'Male' },
    { id: 43, name: 'Ella', surname: 'King', email: 'ellaking@gmail.com', gender: 'Female' },
    { id: 44, name: 'Lucas', surname: 'Perez', email: 'lucasperez@gmail.com', gender: 'Male' }
];

export default users;